#!/usr/bin/env bash
# -------------------------------------------------------------
# Script	:
# Descrição	:
# Versão	: 1.0
# Autor		: Daniel Lima <daniellimafreita@gmail.com>
# Data		: 28/01/25
# Licença	: GNU/GPL v3.0
# -------------------------------------------------------------
# Uso:
# -------------------------------------------------------------


read -p "Digitar um nome: " nome
read -p "Digite um nome de uma revista: " revista
read -p "Digite o nome de uma peça de roupa: " roupa

echo "\
Você escolheu: $nome, $revista, $roupa.
"

read -p "Digite um número de 1 a 3: " numero

frase[1]="$nome saiu da capa da $revista só de $roupa."
frase[2]="$nome só consegue ler a $revista usando $roupa."
frase[3]="$nome aprendeu na revista $revista que usar a $roupa é legal!"

echo "
${frase[$numero]}
"

exit 0
