#!/usr/bin/env bash

clear
echo "Iformações Importantes"
echo "--------------------------"

echo -n "Usuário: "
whoami

echo -n "Hostname: "
hostname

echo -n "Uptime: "
uptime -p

echo -n "Kernal: "
uname -rms

echo "--------------------------"

