#!/usr/bin/env bash
# -------------------------------------------------------------
# Script	:
# Descrição	:
# Versão	: 1.0
# Autor		: Daniel Lima <daniellimafreita@gmail.com>
# Data		: 29/01/25
# Licença	: GNU/GPL v3.0
# -------------------------------------------------------------
# Uso:
# -------------------------------------------------------------

for NOME [in LISTA] 
do
 COMANDOS
done

for NOME [in LISTA]; do COMANDOS; done

(( EXPRESSÃO  ))
