#!/usr/bin/env bash
# -------------------------------------------------------------
# Script	:
# Descrição	:
# Versão	: 1.0
# Autor		: Daniel Lima <daniellimafreita@gmail.com>
# Data		: 29/01/25
# Licença	: GNU/GPL v3.0
# -------------------------------------------------------------
# Uso:
# -------------------------------------------------------------

clear

while trye; do
 clear
 
 echo "1 - Banana"
 echo "2 - Laranja"
 echo "3 - Abacate"
 echo "4 - Sair"
 read -p "Escolha o número da sua opção: " opt

 [[ $opt -eq 4 ]] && break
 echo "Você escolheu ${fruta[(( $opt -1 ))]}"
 
 read -p "Tecle algo para continuar..." continua
done
