#!/usr/bin/env bash
# -------------------------------------------------------------
# Script	:
# Descrição	:
# Versão	: 1.0
# Autor		: Daniel Lima <daniellimafreita@gmail.com>
# Data		: 28/01/25
# Licença	: GNU/GPL v3.0
# -------------------------------------------------------------
# Uso:
# -------------------------------------------------------------

clear

"
**		Exponenciação
*, /, % 	Multimplicação, divisão, resto de divisão
+, - 		Adição, subtração

Digite qualquer expressão com os operadores acima
e tecle enter para efetuar o cálculo.

Exemplo: 2+2
"

read -p "Sua expressão: " expressao

[[ ${#expressao} -lt 1 ]] && exit

# Utilizando o comando 'let'

let calc="$expressao"

echo "
- Utilizando o comando 'let \"expressao\"':

$expressao = $calc
"

# Utilizando o comando composto (( EXPRESSÃO ))

(( calc=$expressao  ))

echo "
- Utilizando o comando composto '(( $expressao ))':

$expressao = $calc
"

# Utilizando a expansão aritmética

calc=$(( $expressao ))

echo "
- Utilizando a expansão aritmética '\$(( $expressao  ))':

$expressao = $calc
"

# Alterando atributo de inteiro 'declare -i var=EXPRESSÃO'

declare -i calc="$expressao"

echo "
- Alterando atributo de inteiro 'declare -i var=\"$expressao\"':

$expressao = $calc
"

declare +i calc

exit 0

